[versions]
androidxCore = "1.9.0"
composeVersion = "1.4.3"
lifecycleVersion = "2.6.1"
coroutinesVersion = "1.6.4"
roomVersion = "2.5.2"
hilt = "2.47"
androidxHiltNavigationCompose = "1.0.0"
accompanistVersion = "0.28.0"
androidGradlePlugin = "8.0.0"
androidLibrary = "7.2.2"
materialThreeVersion = "1.1.0"
androidxNavigation = "2.5.3"
androidxActivity = {strictly = "1.7.1"}
androidxAppCompat = "1.5.1"
androidxCoreSplashscreen = "1.0.0"
androidxLifecycle = "2.6.0-alpha05"
kotlinVersion = "1.8.10"
composeUiTooling = "1.4.2"
composeUiToolingPreview = "1.4.2"
kotlinKapt = "1.8.10"
dataStorePrefsVer = "1.0.0"
androidxTestExt = "1.1.5"
androidxEspresso = "3.5.1"
coreTestingVer = "2.2.0"
googleTruthVer = "1.1.3"
mockkVersion = "1.13.2"
jodaVer = "2.12.2"

[libraries]
android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeVersion" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeVersion" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeVersion" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "composeVersion" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeVersion" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeVersion" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-viewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-viewmodel-savedState = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycleVersion" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-room-test = { group = "androidx.room", name = "room-testing", version.ref = "roomVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
material-three = { group = "androidx.compose.material3", name = "material3", version.ref = "materialThreeVersion" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "dataStorePrefsVer"}
androidx-datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStorePrefsVer" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "coreTestingVer" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
android-test-exts = {group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt"}
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
#androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
#androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRules" }
#androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTestingVer"}
google-truth = {group = "com.google.truth", name="truth", version.ref = "googleTruthVer"}
google-truth-java-exts = { group = "com.google.truth.extensions", name="truth-java8-extension", version.ref = "googleTruthVer"}
mock-test = {group = "io.mockk", name= "mockk-android", version.ref= "mockkVersion" }
mock-agent = { group = "io.mockk", name="mockk-agent", version.ref= "mockkVersion" }
joda-time = { group = "joda-time", name="joda-time", version.ref = "jodaVer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidLibrary" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinKapt"}
